# -*- coding: utf-8 -*-
"""CSC798.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKrGi0xxXWAYX8bPBCC1KkGVYxDf8dXz
"""

# --- Install needed packages (run this cell first) ---
# Install required packages
!pip install --upgrade sdv aif360 fairlearn imbalanced-learn shap lime scikit-learn --quiet
!wget https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv

# --- Imports ---
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from imblearn.over_sampling import SMOTE
from sdv.single_table import CTGANSynthesizer as CTGAN
import shap
from lime.lime_tabular import LimeTabularExplainer
from aif360.datasets import CompasDataset
from fairlearn.metrics import MetricFrame, demographic_parity_difference, equalized_odds_difference
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

# Load UCI Adult Income dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
columns = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship',
           'race','sex','capital-gain','capital-loss','hours-per-week','native-country','income']
adult = pd.read_csv(url, names=columns, na_values=' ?', skipinitialspace=True)

# Basic preprocessing
adult = adult.dropna()
for col in ['workclass','education','marital-status','occupation','relationship','race','sex','native-country','income']:
    adult[col] = LabelEncoder().fit_transform(adult[col])

X_adult = adult.drop('income', axis=1)
y_adult = adult['income']
scaler = StandardScaler()
X_adult_scaled = scaler.fit_transform(X_adult)

import pandas as pd
compas_df = pd.read_csv("compas-scores-two-years.csv")
# You can do any cleaning/preprocessing here, for example:
compas_df = compas_df.dropna(subset=['sex', 'age', 'race', 'priors_count', 'c_charge_degree', 'two_year_recid'])
# Encode categorical variables
from sklearn.preprocessing import LabelEncoder
for col in ['sex', 'race', 'c_charge_degree']:
    compas_df[col] = LabelEncoder().fit_transform(compas_df[col])
X_compas = compas_df[['sex', 'age', 'race', 'priors_count', 'c_charge_degree']]
y_compas = compas_df['two_year_recid']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_compas_scaled = scaler.fit_transform(X_compas)

import zipfile, io, requests
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Download and extract
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00296/dataset_diabetes.zip"
r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))

# Load CSV
diabetes = pd.read_csv(z.open('dataset_diabetes/diabetic_data.csv'))

# Replace '?' with NaN
diabetes = diabetes.replace('?', pd.NA)

# For each column, fill NaN: mode for categorical, median for numeric
for col in diabetes.columns:
    if diabetes[col].dtype == 'object':
        diabetes[col] = diabetes[col].fillna(diabetes[col].mode()[0])
    else:
        diabetes[col] = diabetes[col].fillna(diabetes[col].median())

# Encode all categorical columns
for col in diabetes.select_dtypes(include='object'):
    diabetes[col] = LabelEncoder().fit_transform(diabetes[col])

# Prepare X and y (predict "readmitted" as binary: 1 if readmitted, 0 otherwise)
X_diabetes = diabetes.drop('readmitted', axis=1)
y_diabetes = (diabetes['readmitted'] != 0).astype(int)  # 0 = no, 1 = yes

# Scale features
scaler = StandardScaler()
X_diabetes_scaled = scaler.fit_transform(X_diabetes)

print("Diabetes data loaded, filled, encoded, and scaled!")
print(f"Shape: {X_diabetes_scaled.shape}")

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_diabetes_scaled = scaler.fit_transform(X_diabetes)

from imblearn.over_sampling import SMOTE

def smote_augment(X, y):
    sm = SMOTE(random_state=42)
    X_res, y_res = sm.fit_resample(X, y)
    return X_res, y_res

# Example: Apply to UCI Adult
X_adult_sm, y_adult_sm = smote_augment(X_adult_scaled, y_adult)

from sklearn.model_selection import train_test_split

# For UCI Adult (after SMOTE and scaling)
X_train_adult, X_test_adult, y_train_adult, y_test_adult, idx_train_adult, idx_test_adult = train_test_split(
    X_adult_sm, y_adult_sm, np.arange(len(y_adult_sm)), test_size=0.3, random_state=42)

# Index of 'sex' in your original feature set
sex_idx = list(adult.drop('income', axis=1).columns).index('sex')

# Sensitive attribute values for test set
sex_test_adult = X_adult_sm[idx_test_adult, sex_idx]

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from fairlearn.metrics import demographic_parity_difference, equalized_odds_difference
from sklearn.metrics import accuracy_score

# Helper to get feature index
def get_column_idx(cols, name, default=0):
    if isinstance(cols, pd.Index):
        return cols.get_loc(name) if name in cols else default
    elif isinstance(cols, list):
        return cols.index(name) if name in cols else default
    else:
        return default


## ---------- UCI Adult ----------
# Index for 'sex'
sex_idx = get_column_idx(list(adult.drop('income', axis=1).columns), 'sex')
# Split
X_train_adult, X_test_adult, y_train_adult, y_test_adult = train_test_split(
    X_adult_sm, y_adult_sm, test_size=0.3, random_state=42)
sex_test_adult = X_test_adult[:, sex_idx]
clf_adult = RandomForestClassifier(n_estimators=100, random_state=42)
clf_adult.fit(X_train_adult, y_train_adult)
y_pred_adult = clf_adult.predict(X_test_adult)
print("== UCI Adult (sensitive: sex) ==")
print("Accuracy:", accuracy_score(y_test_adult, y_pred_adult))
print("Demographic Parity Difference:", demographic_parity_difference(y_test_adult, y_pred_adult, sensitive_features=sex_test_adult))
print("Equalized Odds Difference:", equalized_odds_difference(y_test_adult, y_pred_adult, sensitive_features=sex_test_adult))
print("\n")

## ---------- COMPAS ----------
race_idx_compas = get_column_idx(X_compas.columns if hasattr(X_compas, 'columns') else [], 'race', default=2)
X_train_compas, X_test_compas, y_train_compas, y_test_compas = train_test_split(
    X_compas_scaled, y_compas, test_size=0.3, random_state=42)
race_test_compas = X_test_compas[:, race_idx_compas]
clf_compas = RandomForestClassifier(n_estimators=100, random_state=42)
clf_compas.fit(X_train_compas, y_train_compas)
y_pred_compas = clf_compas.predict(X_test_compas)
print("== COMPAS (sensitive: race) ==")
print("Accuracy:", accuracy_score(y_test_compas, y_pred_compas))
print("Demographic Parity Difference:", demographic_parity_difference(y_test_compas, y_pred_compas, sensitive_features=race_test_compas))
print("Equalized Odds Difference:", equalized_odds_difference(y_test_compas, y_pred_compas, sensitive_features=race_test_compas))
print("\n")

## ---------- Diabetes ----------
race_idx_diabetes = get_column_idx(X_diabetes.columns if hasattr(X_diabetes, 'columns') else [], 'race', default=2)
X_train_diab, X_test_diab, y_train_diab, y_test_diab = train_test_split(
    X_diabetes_scaled, y_diabetes, test_size=0.3, random_state=42)
race_test_diab = X_test_diab[:, race_idx_diabetes]
clf_diab = RandomForestClassifier(n_estimators=100, random_state=42)
clf_diab.fit(X_train_diab, y_train_diab)
y_pred_diab = clf_diab.predict(X_test_diab)
print("== Diabetes (sensitive: race) ==")
print("Accuracy:", accuracy_score(y_test_diab, y_pred_diab))
print("Demographic Parity Difference:", demographic_parity_difference(y_test_diab, y_pred_diab, sensitive_features=race_test_diab))
print("Equalized Odds Difference:", equalized_odds_difference(y_test_diab, y_pred_diab, sensitive_features=race_test_diab))

def counterfactual_flip(X, feature_index):
    X_flip = X.copy()
    X_flip[:, feature_index] = 1 - X_flip[:, feature_index]
    return X_flip

# Example: flip 'sex' in UCI Adult (index for 'sex')
sex_idx = list(adult.drop('income', axis=1).columns).index('sex')
X_adult_cf = counterfactual_flip(X_adult_scaled, sex_idx)

from sdv.metadata import SingleTableMetadata
from sdv.single_table import CTGANSynthesizer

# 1. Generate metadata
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data=adult)

# 2. Train CTGAN
ctgan = CTGANSynthesizer(metadata, epochs=10)
ctgan.fit(adult)
synthetic_adult = ctgan.sample(1000)

def train_and_evaluate(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    clf = RandomForestClassifier(n_estimators=100).fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    return X_test, y_test, y_pred, clf

# Example for UCI Adult (after SMOTE)
X_test_adult, y_test_adult, y_pred_adult, clf_adult = train_and_evaluate(X_adult_sm, y_adult_sm)
# COMPAS
X_test_compas, y_test_compas, y_pred_compas, clf_compas = train_and_evaluate(X_compas_scaled, y_compas)
# Diabetes
X_test_diabetes, y_test_diabetes, y_pred_diabetes, clf_diabetes = train_and_evaluate(X_diabetes_scaled, y_diabetes)

def show_metrics(y_test, y_pred, name):
    print(f"== {name} ==")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, zero_division=0))
    print("Recall:", recall_score(y_test, y_pred, zero_division=0))
    print("F1-score:", f1_score(y_test, y_pred, zero_division=0))

show_metrics(y_test_adult, y_pred_adult, "UCI Adult (SMOTE)")
show_metrics(y_test_compas, y_pred_compas, "COMPAS")
show_metrics(y_test_diabetes, y_pred_diabetes, "Diabetes")

from fairlearn.metrics import demographic_parity_difference, equalized_odds_difference
from sklearn.metrics import accuracy_score

# Helper to get feature index robustly
def get_column_idx(cols, name, default=0):
    if isinstance(cols, pd.Index):
        return cols.get_loc(name) if name in cols else default
    elif isinstance(cols, list):
        return cols.index(name) if name in cols else default
    else:
        return default

## ---------- UCI Adult ----------
sex_idx = get_column_idx(list(adult.drop('income', axis=1).columns), 'sex')
X_train_adult, X_test_adult, y_train_adult, y_test_adult = train_test_split(
    X_adult_sm, y_adult_sm, test_size=0.3, random_state=42)
sex_test_adult = X_test_adult[:, sex_idx]
clf_adult = RandomForestClassifier(n_estimators=100, random_state=42)
clf_adult.fit(X_train_adult, y_train_adult)
y_pred_adult = clf_adult.predict(X_test_adult)
print("== UCI Adult (sensitive: sex) ==")
print("Accuracy:", accuracy_score(y_test_adult, y_pred_adult))
print("Demographic Parity Difference:", demographic_parity_difference(y_test_adult, y_pred_adult, sensitive_features=sex_test_adult))
print("Equalized Odds Difference:", equalized_odds_difference(y_test_adult, y_pred_adult, sensitive_features=sex_test_adult))
print("\n")

## ---------- COMPAS ----------
race_idx_compas = get_column_idx(X_compas.columns if hasattr(X_compas, 'columns') else [], 'race', default=2)
X_train_compas, X_test_compas, y_train_compas, y_test_compas = train_test_split(
    X_compas_scaled, y_compas, test_size=0.3, random_state=42)
race_test_compas = X_test_compas[:, race_idx_compas]
clf_compas = RandomForestClassifier(n_estimators=100, random_state=42)
clf_compas.fit(X_train_compas, y_train_compas)
y_pred_compas = clf_compas.predict(X_test_compas)
print("== COMPAS (sensitive: race) ==")
print("Accuracy:", accuracy_score(y_test_compas, y_pred_compas))
print("Demographic Parity Difference:", demographic_parity_difference(y_test_compas, y_pred_compas, sensitive_features=race_test_compas))
print("Equalized Odds Difference:", equalized_odds_difference(y_test_compas, y_pred_compas, sensitive_features=race_test_compas))
print("\n")

## ---------- Diabetes ----------
race_idx_diabetes = get_column_idx(X_diabetes.columns if hasattr(X_diabetes, 'columns') else [], 'race', default=2)
X_train_diab, X_test_diab, y_train_diab, y_test_diab = train_test_split(
    X_diabetes_scaled, y_diabetes, test_size=0.3, random_state=42)
race_test_diab = X_test_diab[:, race_idx_diabetes]
clf_diab = RandomForestClassifier(n_estimators=100, random_state=42)
clf_diab.fit(X_train_diab, y_train_diab)
y_pred_diab = clf_diab.predict(X_test_diab)
print("== Diabetes (sensitive: race) ==")
print("Accuracy:", accuracy_score(y_test_diab, y_pred_diab))
print("Demographic Parity Difference:", demographic_parity_difference(y_test_diab, y_pred_diab, sensitive_features=race_test_diab))
print("Equalized Odds Difference:", equalized_odds_difference(y_test_diab, y_pred_diab, sensitive_features=race_test_diab))

# SHAP for UCI Adult
explainer = shap.TreeExplainer(clf_adult)
shap_values = explainer.shap_values(X_test_adult)
shap.summary_plot(shap_values, X_test_adult, feature_names=list(adult.drop('income', axis=1).columns), show=False)
import matplotlib.pyplot as plt; plt.show()

# LIME for UCI Adult
explainer_lime = LimeTabularExplainer(X_adult_sm, feature_names=list(adult.drop('income', axis=1).columns), class_names=['<=50K','>50K'], discretize_continuous=True)
exp = explainer_lime.explain_instance(X_test_adult[0], clf_adult.predict_proba, num_features=5)
exp.show_in_notebook()

from scipy import stats

# Example: t-test between SMOTE vs. original F1 scores for Adult (use your real arrays in practice)
f1_smote = [f1_score(y_test_adult, y_pred_adult)] * 5  # Placeholder
f1_orig = [0.81, 0.82, 0.80, 0.82, 0.81]  # Placeholder
t_stat, p_val = stats.ttest_ind(f1_smote, f1_orig)
print(f"t-statistic: {t_stat:.3f}, p-value: {p_val:.4f}")

# Confidence interval for disparate impact (example)
di_values = np.array([0.78, 0.82, 0.81, 0.79, 0.80])
mean = np.mean(di_values)
sem = stats.sem(di_values)
ci = stats.t.interval(0.95, len(di_values)-1, loc=mean, scale=sem)
print(f"Disparate Impact Mean: {mean:.3f}, 95% CI: ({ci[0]:.3f}, {ci[1]:.3f})")



